#!/bin/sh
# File generated by ocamlbuild

cd /home/brandon/Dev/03_pascalLIGO/01_basic/OUnit

rm -f foo.cmi
rm -f foo.cmo
rm -f temp.cmi
rm -f temp.cmo
# Also clean the script itself
rm -f /home/brandon/Dev/03_pascalLIGO/01_basic/OUnit/_build/sanitize.sh
